name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    # Install .NET Core
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101

    # Restore projects
    - name: Restore projects
      run: dotnet restore

    # Build projects
    - name: Build projects
      run: dotnet build --configuration Release --no-restore

    # Run test projects
    - name: Run test projects
      run: dotnet test SIO-Translator.sln --configuration Release --no-restore --no-build --verbosity normal --filter Category=Unit -- xunit.parallelizeAssembly=true